### ISSUE TITLE
Error during loading

### ISSUE THREAD

**Issue by AndreySV** [gmerlino/wamp-wireshark#1]
Lua: Error during loading:
wswamp-dis... :89: bad argument #1 to 'new' (field_nw: a field with this name must exist)

Version 2.6.1 (Git v2.6.1 packaged as 2.6.1-1)  with Lua 5.2.4

**Comment by gmerlino** [comment]
I noticed that on my side - Version 2.6.2 (v2.6.2-0-g1b3cedbc) with Lua 5.2.4 running on Mac OS X 10.13.6, build 17G65 (Darwin 17.7.0) - the same error happens when renaming as you did (wswamp -> ws-wamp), whereas it does not happen with another rename (ws_wamp) I tried.

Can you try on your side under Linux?
In case it works for you too, I would suggest another pull accordingly.

Thanks and regards

**Comment by AndreySV** [comment]
rename to ws_wampdissector.lua works on GNU/Linux. 
I've updated pull request.
